### PR TITLE
Added Support for AsyncDNSServer

### PR DESCRIPTION
**Pull request by debsahu**
Need to install https://github.com/devyte/ESPAsyncDNSServer and
https://github.com/me-no-dev/ESPAsyncUDP

* Enchancement proposed in
https://github.com/alanswx/ESPAsyncWiFiManager/issues/20

### CODE REVIEW

**Comment by debsahu** [comment]
I propose to create a separate branch for this. The reasoning being if one chooses to use **AsyncDNSServer**, they can't use **DNSServer**(DNSServer.h) in their code.

**Comment by debsahu** [comment]
@alanswx now users can uncomment `//#define USE_EADNS` in "ESPAsyncWiFiManager.h" to use AsyncDNSServer. Is this what you had in mind?

**Comment by alanswx** [comment]
Can we check for the include from their .h in our include maybe?  Or does that seem like a hacky side  effect? So to turn on async you would include their header before ours and ours would kick in? Can that work? I haven’t thought through the logic. Maybe not because our header would not include it up front?

**Comment by debsahu** [comment]
I have put in a PR https://github.com/devyte/ESPAsyncDNSServer/pull/2 in ESPASyncDNSServer repo, so that both AsyncDNSServer and DNSServer can be included and we can have different functions for different DNS types.

**Pull request merged**
