### PR TITLE
moved code into src, fixed warnings and some cosmetics

### PR DESCRIPTION
**Pull request by hmronline**
@alanswx please kindly review these proposed (minor) changes; I've tested this and its working properly.

Thanks!

### CODE REVIEW

**Comment by hmronline** [comment]
Thix fixes #71

**Comment by alanswx** [comment]
Can you look at the other open issues? You must be more familiar with the code now.  Thanks

**Comment by alanswx** [comment]
Someone said the build is failing now?

**Comment by hmronline** [comment]
ok, I'll take a look at it.

**Comment by hmronline** [comment]
> Can you look at the other open issues? You must be more familiar with the code now. Thanks

sure, I'm still getting familiar but I'll try to contribute as much as possible

**Pull request merged**
